### ISSUE TITLE
The latest version of keyring does not install all requirements on linux

### ISSUE THREAD

**Issue by PrimozGodec** [conda-forge/keyring-feedstock#9]
The latest version of keyring does not install all requirements on Linux. Look at the Circleci build of Orange3 in this pull request https://github.com/conda-forge/orange3-feedstock/pull/45.

**Comment by ccordoba12** [comment]
It has never been possible to use the keyring package on Linux (you can take a look at git history).

The problem is keyring depends on secretstorage, which depends on python-dbus, which is very hard to compile.

We're waiting for a new release of secretstorage, which will depend on a pure python implementation of dbus bindings.

**Comment by ocefpaf** [comment]
Closing this as stale.

**Comment by ccordoba12** [comment]
This is fixed now for Python 3.
